[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_program_example = "FhjBVpnwE8R6wBLS1X2YEfTXzjednen5MDFUDoeoiJG7"

[programs.devnet]
anchor_program_example = "FhjBVpnwE8R6wBLS1X2YEfTXzjednen5MDFUDoeoiJG7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
